import React from 'react';

function FAQ() {

    return (
      <div className="FAQ">
        <div className="faqTitle">
          <h1 className="faqH1">Frequently Asked Questions</h1>
          <p className="faqQ"><b>Where are your classes held?</b></p>
          <p className="faqA">My classes are held at the <a href="https://www.greatfermentations.com"  target="_blank" rel="noreferrer" id="greatFermLink"><b>Great Fermentations Education Center</b></a>  but I am free to teach private functions anywhere with the right amount of space. Great Fermentation is a beer & wine making supply shop with an education center used to teach a variety of classes from beer, wine, cheese and even Kombucha. The commercially-equipped kitchen makes it an excellent place to teach these bread classes.</p>
          <p className="faqQ"><b>How much are your classes and where can I see the schedule to sign up? </b></p>
          <p className="faqA">Classes range from $35 to $55 and can be found at <a href="https://www.eventbrite.com/" target="_blank" rel="noreferrer"><b>Eventbrite</b></a>  or  <a href="https://www.greatfermentations.com/events/"target="_blank" rel="noreferrer"><b>Great Fermentations</b></a> (all are ticketed through Event Brite)</p>
          <p className="faqQ"><b>I have never baked bread before but want to try. Can you recommend a beginner-level class? </b></p>
          <p className="faqA">The Easy Italian or Easy Wheat bread classes are great for beginners. While these are simple, tasty loaves you’ll still learn the techniques to help you bake any yeast bread. I still bake these breads regularly because they are easy & delicious.</p>
          <p className="faqQ"><b> I have never baked bread before – can I try your sourdough bread class? </b></p>
          <p className="faqA">Yes, you can- but it is a rather advanced class and is nothing like traditional yeast breads. There is a lot of time involved with a series of small steps and very little work. Folks with no baking experience have done very well and if you follow the process you can certainly succeed. This class will not help you with yeast breads because the process is so different. I regularly hear “Well I wasn’t expecting this!” because it is so different than yeast baking.  The steps and time involved can look complicated but I help you understand the entire process and make it work around your schedule.  Having some baking experience is very helpful though. </p>
          <p className="faqQ"><b>What can I expect when I attend your classes?</b></p>
          <p className="faqA">You can expect to see every step of the baking process from mixing, kneading, proofing, baking & even tasting. I have a Power Point presentation for each class that helps cover all the material and stay on track. You’ll learn the technique, some science and ways to make bread-baking work around your schedule. We’ll talk about the ingredients, their role in the recipe and you will mix your dough right there in class if you choose.  We squeeze most baking processes into a 2-hour class. At the end of each class is what I call “The Delicious Part of the Program” with meats, cheeses and condiments to pair with that bread.  </p>
          <p className="faqQ"><b>What’s included in the classes? </b></p>
          <p className="faqA">All ingredients are provided pre-measured so you can mix right there in class to take your dough home and bake later. Mixing bowls and utensils are all provided. I provide the recipe in printed form and follow up with the electronic version via e-mail. You’ll also receive extra yeast or sourdough starter to take home depending on the class. </p>
          <p className="faqQ"><b>What do I need to bring to class?</b></p>
          <p className="faqA">Usually all you need is a 6qt bowl with a tight-fitting lid to bring your dough home in. If you forget I can give you a Ziplock bag to use that will work fine until you get home.</p>
          <p className="faqQ"><b>I have other plans later the day of my class- can I just take the ingredients home to mix tomorrow?</b></p>
          <p className="faqA">Absolutely- I stress that folks have the time that day to finish their bread or simply wait until it’s convenient for them. You will still see every step of the process. Please don’t start something you can’t finish with good results.</p>
          <p className="faqQ"><b>What do your classes offer that internet recipes or YouTube videos can’t provide? </b></p>
          <p className="faqA">I pass along years of my personal baking tips, tricks and ways to make great bread every time. You’ll learn the process, technique and ways to make this convenient for you.  I also pass along money-saving tips that will keep you baking for much less dough. (get it?) There’s a fair amount of science going on and you’ll learn about that too.  I often hear “I tried this online recipe and it failed miserably”.  You’ll learn how to make those “Internet Recipes” actually turn out…  I teach the fundamentals of baking so you can apply them to any bread you want to attempt.</p>
          <p className="faqQ"><b>Do you teach a Gluten-Free bread class? </b></p>
          <p className="faqA">No. Gluten-Free breads are a mixture of specialty flours and binding agents like Xanathan gum which itself can be expensive. Most GF recipes call for almond flour and I am allergic to nuts so experimenting is out of the question for me.  GF bread does not contain yeast because yeast has gluten and baking soda or baking powder is used to leaven (rise) the bread.  GF bread will not have that yeasty flavor & aroma you are expecting.  GF bread is essentially soda bread using a variety of specialty flours that do their best to resemble bread. While I know several Celiac-diagnosed individuals and sympathize with their condition I do not have a need to branch out to GF baking. From what I have been told several decent commercially-baked versions of GF bread are available.</p>
          <p className="faqQ"><b>Do you sell your bread or cater events?</b></p>
          <p className="faqA">No- I get asked this a lot. The time involved with making bread in quantity would require me to charge a lot for that bread. There are also Health Department regulations that I’d rather not deal with. I prefer just to teach classes and spread my passion for bread-baking.</p>
          <p className="faqQ"><b>Are you on Facebook?</b></p>
          <p className="faqA">Yes- you can find me on Facebook as <a href="https://www.facebook.com/Frankthebreadguy" target="_blank" rel="noreferrer"><b>Frank the Bread Guy</b></a>. This page is mainly just bread pictures, tips & tricks that I share along the way with the public.  I do post my class schedule there and any changes. I do not market to people ever so give me a “Like”. My classes are actually marketed for me by Jenny at Great Fermentations with their website and Event Brite. Not only that I’m bad at self-promotion. 😊 Feel free to follow me on Facebook.</p>
          <p className="faqQ"><b>Would you teach a class at my house or church if I gathered enough attendees?</b></p>
          <p className="faqA">Yes - I am free to teach classes anywhere I like. Great Fermentations is ideal because it is a commercially-equipped kitchen with lots of counter space for folks to mix/knead their dough. I have taught classes at churches and simply alter the format to where they see all steps but take the pre-measured ingredients home to mix later. You’ll still see every step, get the recipe, the ingredients, see the presentation and be able to interact throughout the process. You just will not be kneading any dough in class. I need a minimum of 4 people because there is a lot of preparation involved in these classes. </p>
        </div>
      </div>
    );
  }
  
  export default FAQ;